language: python

matrix:
    include:
        - os: linux
          python: 3.2
        - os: linux
          python: 3.3
        - os: linux
          python: 3.4
        - os: linux
          python: 3.5
        - os: linux
          python: 3.6
        - os: linux
          dist: xenial
          python: 3.7
        - os: osx
          python: 3.2
        - os: osx
          python: 3.3
        - os: osx
          python: 3.4
        - os: osx
          python: 3.5
script:
    - python -c "import sys; print(sys.version)"
