language: python

matrix:
    include:
#        - os: linux
#          env: PY=python3
#          python: 3.2
#        - os: linux
#          env: PY=python3
#          python: 3.3
        - os: linux
          env: PY=python3
          python: 3.4
#        - os: linux
#          python: 3.5
#        - os: linux
#          python: 3.6
        - os: linux
          dist: xenial
          env: PY=python3
          python: 3.7
#        - os: osx
#          python: 3.2
#        - os: osx
#          python: 3.3
#        - os: osx
#          python: 3.4
        - os: osx
          language: generic
          env: PYTHON=3.5.1
          env: PY=python3
        - os: windows
          language: sh
          env: PY=py
before_install:
    - ./.travis/install.sh
script:
    - $PY -c "import sys; print(sys.version)"
